FROM cyberprobe-debian-jessie-dev
ARG SRC
ARG VERSION
ADD ${SRC} /usr/local/src/cyberprobe/
WORKDIR /usr/local/src/cyberprobe/cyberprobe-${VERSION}
RUN sed -i 's/libreadline7/libreadline6/' debian/control
RUN sed -i 's/libboost-program-options1.62.0/libboost-program-options1.55.0/' debian/control
RUN autoreconf -fi
RUN ./configure --prefix=/usr/local
RUN DEB_CXXFLAGS_APPEND=-std=c++11 make -f pkg.mk deb
