FROM cyberprobe-debian-dev
ARG GIT_VERSION=HEAD
RUN mkdir -p /usr/local/src/cyberprobe
WORKDIR /usr/local/src/cyberprobe
RUN git clone http://github.com/cybermaggedon/cyberprobe .; git checkout ${GIT_VERSION}
RUN autoreconf -fi
RUN ./configure --prefix=/usr/local
RUN make check
RUN make -f pkg.mk deb
