FROM fedora:30
RUN dnf install -y git autoconf automake
RUN dnf install -y texinfo-tex
RUN dnf install -y libpcap-devel boost-devel gcc-c++
RUN dnf install -y lua-devel 
RUN dnf install -y ncurses-devel readline-devel 
RUN dnf install -y lua-json lua-socket
RUN dnf install -y texinfo texlive
RUN dnf install -y python
RUN dnf install -y tcpdump tar
RUN dnf install -y libtool make
RUN dnf install -y rpm-build
RUN dnf install -y openssl-devel
RUN dnf install -y protobuf-compiler protobuf protobuf-c protobuf-devel
RUN dnf install -y grpc grpc-devel grpc-plugins
RUN dnf install -y which