
FROM fedora:24

COPY product/fedora-cyberprobe-0.63-1.fc24.x86_64.rpm cyberprobe.rpm

RUN dnf install -y cyberprobe.rpm
RUN dnf install -y lua-socket lua-json
RUN dnf install -y tar
RUN dnf install -y luarocks
RUN dnf install -y cppzmq-devel
RUN dnf install -y gcc
RUN dnf install -y lua-devel
RUN dnf install -y findutils
RUN luarocks install lzmq
RUN luarocks install uuid

CMD cybermon 9000 /etc/cyberprobe/zeromq.lua

# cybermon receiver port.
EXPOSE 9000

# ZeroMQ pub/sub port.
EXPOSE 5555

