FROM cyberprobe-ubuntu-bionic-dev
ARG SRC
ARG VERSION
ADD ${SRC} /usr/local/src/cyberprobe/
WORKDIR /usr/local/src/cyberprobe/cyberprobe-${VERSION}
RUN autoreconf -fi
RUN ./configure --prefix=/usr/local
RUN make -f pkg.mk deb
