FROM cyberprobe-ubuntu-artful-dev
ARG SRC
ARG VERSION
COPY ubuntu-artful/systemd.pc /usr/share/pkgconfig/systemd.pc
ADD ${SRC} /usr/local/src/cyberprobe/
WORKDIR /usr/local/src/cyberprobe/cyberprobe-${VERSION}
RUN autoreconf -fi
RUN ./configure --prefix=/usr/local
RUN make -f pkg.mk deb
