FROM cyberprobe-debian-wheezy-dev
ARG SRC
ARG VERSION
ADD ${SRC} /usr/local/src/cyberprobe/
WORKDIR /usr/local/src/cyberprobe/cyberprobe-${VERSION}
RUN sed -i 's/libreadline7/libreadline6/' debian/control
RUN autoreconf -fi
RUN ./configure --prefix=/usr/local
RUN make -f pkg.mk deb
