FROM fedora:22
RUN dnf install -y git autoconf automake
RUN dnf install -y texinfo-tex
RUN dnf install -y libpcap-devel boost-devel gcc-c++
RUN dnf install -y expat-devel lua-devel 
RUN dnf install -y ncurses-devel readline-devel 
RUN dnf install -y lua-socket
RUN dnf install -y texinfo texlive
RUN dnf install -y luarocks
RUN dnf install -y python
RUN dnf install -y tcpdump tar
RUN dnf install -y libtool make
RUN dnf install -y rpm-build
RUN dnf install -y openssl-devel
RUN dnf install -y cppzmq-devel
RUN luarocks install lzmq
RUN luarocks install redis-lua
RUN luarocks install uuid
RUN luarocks install sha1
RUN luarocks install luajson
